services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    F0ska\AutoGridTestBundle\:
        resource: '../src/{Controller/*,DataFixtures/*,EventSubscriber/*,Repository/*,Service/*,Twig/*}'
        autowire: true
        autoconfigure: true
